// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: action_data.proto

package modules

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProjectType int32

const (
	ProjectType_CLIENT ProjectType = 0
	ProjectType_SERVER ProjectType = 1
)

// Enum value maps for ProjectType.
var (
	ProjectType_name = map[int32]string{
		0: "CLIENT",
		1: "SERVER",
	}
	ProjectType_value = map[string]int32{
		"CLIENT": 0,
		"SERVER": 1,
	}
)

func (x ProjectType) Enum() *ProjectType {
	p := new(ProjectType)
	*p = x
	return p
}

func (x ProjectType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProjectType) Descriptor() protoreflect.EnumDescriptor {
	return file_action_data_proto_enumTypes[0].Descriptor()
}

func (ProjectType) Type() protoreflect.EnumType {
	return &file_action_data_proto_enumTypes[0]
}

func (x ProjectType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProjectType.Descriptor instead.
func (ProjectType) EnumDescriptor() ([]byte, []int) {
	return file_action_data_proto_rawDescGZIP(), []int{0}
}

type ActionCreateData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProjectType    ProjectType `protobuf:"varint,1,opt,name=projectType,proto3,enum=modules.ProjectType" json:"projectType,omitempty"`
	Language       string      `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	GameName       string      `protobuf:"bytes,3,opt,name=gameName,proto3" json:"gameName,omitempty"`
	Url            *string     `protobuf:"bytes,4,opt,name=url,proto3,oneof" json:"url,omitempty"`                       // only needed for clients
	LibraryVersion *string     `protobuf:"bytes,5,opt,name=libraryVersion,proto3,oneof" json:"libraryVersion,omitempty"` // empty -> use latest
}

func (x *ActionCreateData) Reset() {
	*x = ActionCreateData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_action_data_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActionCreateData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionCreateData) ProtoMessage() {}

func (x *ActionCreateData) ProtoReflect() protoreflect.Message {
	mi := &file_action_data_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionCreateData.ProtoReflect.Descriptor instead.
func (*ActionCreateData) Descriptor() ([]byte, []int) {
	return file_action_data_proto_rawDescGZIP(), []int{0}
}

func (x *ActionCreateData) GetProjectType() ProjectType {
	if x != nil {
		return x.ProjectType
	}
	return ProjectType_CLIENT
}

func (x *ActionCreateData) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *ActionCreateData) GetGameName() string {
	if x != nil {
		return x.GameName
	}
	return ""
}

func (x *ActionCreateData) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *ActionCreateData) GetLibraryVersion() string {
	if x != nil && x.LibraryVersion != nil {
		return *x.LibraryVersion
	}
	return ""
}

var File_action_data_proto protoreflect.FileDescriptor

var file_action_data_proto_rawDesc = []byte{
	0x0a, 0x11, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x22, 0xe3, 0x01, 0x0a,
	0x12, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x64,
	0x61, 0x74, 0x61, 0x12, 0x36, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x6d, 0x6f, 0x64, 0x75, 0x6c,
	0x65, 0x73, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b,
	0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c,
	0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c,
	0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x15, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x88, 0x01, 0x01, 0x12, 0x2b, 0x0a, 0x0e, 0x6c, 0x69,
	0x62, 0x72, 0x61, 0x72, 0x79, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x01, 0x52, 0x0e, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x42, 0x06, 0x0a, 0x04, 0x5f, 0x75, 0x72, 0x6c, 0x42,
	0x11, 0x0a, 0x0f, 0x5f, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x56, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x2a, 0x25, 0x0a, 0x0b, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x4c, 0x49, 0x45, 0x4e, 0x54, 0x10, 0x00, 0x12, 0x0a, 0x0a,
	0x06, 0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x10, 0x01, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2f, 0x6d,
	0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_action_data_proto_rawDescOnce sync.Once
	file_action_data_proto_rawDescData = file_action_data_proto_rawDesc
)

func file_action_data_proto_rawDescGZIP() []byte {
	file_action_data_proto_rawDescOnce.Do(func() {
		file_action_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_action_data_proto_rawDescData)
	})
	return file_action_data_proto_rawDescData
}

var file_action_data_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_action_data_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_action_data_proto_goTypes = []interface{}{
	(ProjectType)(0),         // 0: modules.ProjectType
	(*ActionCreateData)(nil), // 1: modules.action_create_data
}
var file_action_data_proto_depIdxs = []int32{
	0, // 0: modules.action_create_data.projectType:type_name -> modules.ProjectType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_action_data_proto_init() }
func file_action_data_proto_init() {
	if File_action_data_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_action_data_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActionCreateData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_action_data_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_action_data_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_action_data_proto_goTypes,
		DependencyIndexes: file_action_data_proto_depIdxs,
		EnumInfos:         file_action_data_proto_enumTypes,
		MessageInfos:      file_action_data_proto_msgTypes,
	}.Build()
	File_action_data_proto = out.File
	file_action_data_proto_rawDesc = nil
	file_action_data_proto_goTypes = nil
	file_action_data_proto_depIdxs = nil
}
